imports:
    - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml
    - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true
#jobs:
#  server:
#    sources:
#      techempower:
#        repository: https://github.com/gradx/GenieDotNet.git
#        branchOrCommit: main
#    dockerFile: docker\server\Dockerfile
#    dockerImageName: server
#    dockerContextDirectory: docker\server
#    port: 80

jobs:
  server:
#    sources:
#      hello-sample:
#        localFolder: ../
#    project: hello-sample/Genie.Web.Api/Genie.Web.Api.csproj
    source:
      hello-sample:
          repository: https://github.com/gradx/GenieDotNet.git
          branchOrCommit: main
      dockerFile: docker\server\Dockerfile
      dockerImageName: server
      dockerContextDirectory: docker\server
 #   readyStateText: Now listening on
    noClean: true
    port: 80
  kafka:
    source:
      repository: https://github.com/gradx/GenieDotNet.git
      branchOrCommit: main
      dockerFile: docker\kafka\Dockerfile
      dockerImageName: kafka
      dockerContextDirectory: docker\kafka
    readyStateText: Welcome to the Bitnami
    noClean: true
  registry:
    source:
      repository: https://github.com/gradx/GenieDotNet.git
      branchOrCommit: main
      dockerFile: docker\registry\Dockerfile
      dockerImageName: registry
      dockerContextDirectory: docker\registry
    readyStateText: Server started, listening for requests
    noClean: true
scenarios:
  hello:
#    db:
#      job: kafka
#    main:
#      job: registry
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 80
        path: /test

profiles:
  local:
    jobs:
      main:
        job: registry 
      application:
        endpoints: 
          - http://localhost:5010
      load:
        endpoints: 
          - http://localhost:5010