<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Net.IBM.Data.Db2" Version="8.0.0.300" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Genie.Core\Genie.Core.csproj" />
  </ItemGroup>

</Project>
