<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.68.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Proto.Actor" Version="1.7.0" />
    <PackageReference Include="Proto.Cluster" Version="1.7.0" />
    <PackageReference Include="Proto.Cluster.CodeGen" Version="1.7.0" />
    <PackageReference Include="Proto.Cluster.Consul" Version="1.7.0" />
    <PackageReference Include="Proto.Cluster.TestProvider" Version="1.7.0" />
    <PackageReference Include="Proto.Remote" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Genie.Adapters.Brokers\Genie.Adapters.Brokers.Kafka\Genie.Adapters.Brokers.Kafka.csproj" />
    <ProjectReference Include="..\Genie.Common\Genie.Common.csproj" />
    <ProjectReference Include="..\Genie.Core\Genie.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Grains\ActorGrain.proto" />
  </ItemGroup>

  <ItemGroup>
	  <ProtoGrain Include="Grains\ActorGrain.proto" />
  </ItemGroup>

</Project>
