<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aeron.Client" Version="1.40.0" />
    <PackageReference Include="Aeron.Cluster" Version="1.40.0" />
    <PackageReference Include="Aeron.Driver" Version="1.40.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Genie.Adapters.Serializers\Genie.Adapters.Serializers.Avro\Genie.Adapters.Serializers.Avro.csproj" />
    <ProjectReference Include="..\..\Genie.Core\Genie.Core.csproj" />
  </ItemGroup>


</Project>
