
networks:
  app-tier:
    driver: bridge

services:
#    pulsar:
#      image: 'apachepulsar/pulsar:3.3.0'
#      networks:
#        - app-tier
#      ports:
#        - "6650:6650"
#        - "8080:8080"
#      hostname: pulsar
#      command: bin/pulsar standalone
    kafka:
      image: 'bitnami/kafka:latest'
#      networks:
#        - app-tier
      ports:
        - "9092:9092"
#        - "9093:9093"
        - "29092:29092"
#      hostname: kafka
      environment:
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=CONTROLLER://:9092,BROKER://0.0.0.0:29092
        - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka:29092
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9092
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_INTER_BROKER_LISTENER_NAME=BROKER
    schema-registry:
      image: confluentinc/cp-schema-registry:7.6.1
#      networks:
#        - app-tier
      ports:
        - "8081:8081"
#      hostname: registry
      depends_on:
         - kafka
      environment:
        #- SCHEMA_REGISTRY_DEFAULT_KAFKA_BROKERS=PLAINTEXT://kafka:9092
        #- SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092
        - SCHEMA_REGISTRY_HOST_NAME=registry
        - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
        - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:29092