<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetMQ" Version="4.0.1.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Genie.Adapters.Serializers\Genie.Adapters.Serializers.Avro\Genie.Adapters.Serializers.Avro.csproj" />
    <ProjectReference Include="..\..\Genie.Core\Genie.Core.csproj" />
  </ItemGroup>

</Project>
